CONFIG_ZMK_SLEEP=y
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
CONFIG_ZMK_KEYBOARD_NAME="Typhon"
CONFIG_ZMK_HID_CONSUMER_REPORT_USAGES_BASIC=y

# Boost the radio power to maximum (Standard is usually 0 or +4)
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# Improves compatibility with macOS specifically
CONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y